# Generated by Django 5.0.2 on 2024-03-02 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("login_auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "MASCULINO"), ("F", "FEMININO")], max_length=2
                    ),
                ),
                ("country", models.CharField(max_length=200)),
                ("state", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=200)),
                ("neighborhood", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("address_number", models.CharField(max_length=200)),
            ],
        ),
    ]
