# Generated by Django 5.0.2 on 2024-03-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_brand_description_alter_category_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clothingimage",
            name="principal",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="clothingimage",
            name="image",
            field=models.ImageField(upload_to="media/"),
        ),
    ]
