# Generated by Django 5.0.2 on 2024-07-05 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_remove_clothes_colors_clothing_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clothes_colors",
            name="clothing",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="colors",
                to="main.clothing",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clothes_colors",
            name="count",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clothes_sizes",
            name="clothing",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sizes",
                to="main.clothing",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clothes_sizes",
            name="count",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Stock",
        ),
    ]
