# Generated by Django 4.1.1 on 2024-07-19 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_clothes_colors_clothing_clothes_colors_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='color',
            field=models.ForeignKey(default='#fff', on_delete=django.db.models.deletion.CASCADE, to='main.clothes_colors'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='size',
            field=models.ForeignKey(default='M', on_delete=django.db.models.deletion.CASCADE, to='main.clothes_sizes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clothes_colors',
            name='clothing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='main.clothing'),
        ),
        migrations.AlterField(
            model_name='clothes_colors',
            name='count',
            field=models.IntegerField(verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='clothes_sizes',
            name='clothing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='main.clothing'),
        ),
        migrations.AlterField(
            model_name='clothes_sizes',
            name='count',
            field=models.IntegerField(verbose_name='Quantidade'),
        ),
    ]
