# Generated by Django 5.1.1 on 2024-09-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_favorites_session_id_alter_favorites_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
